# Build settings
markdown: kramdown

exclude:
  - vendor

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Social Info
twitter_username: callisto

share_image:      /images/Assets/masthead_2.png
